@host=https://localhost:5211

GET https://localhost:5211/Dinner
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjZmNTczZi04YWIzLTQ2NTEtOWIwYy05NWE1MzAxNjBjYmIiLCJnaXZlbl9uYW1lIjoiVmlzaGFsIiwiZmFtaWx5X25hbWUiOiJTaW5naCIsImp0aSI6IjFlN2EwOTA4LTBjZjMtNGQ3Yi05YzQ5LTNmOGU3ZDllYTRmZiIsImV4cCI6MTcyNTIwMjk1MCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.Gz2UXexQkRPPHe9Xa7uBo9NahlFYlO_HW5SOvJDPYFs